In [1]:
import torch
from torch import tensor

In [78]:
class Module:
    def __call__(*args):
        self.in=args[0]
        self.out=self.forward(args)
        return self.out

In [79]:
class Linear(Module):
    def __init__(in_cannels,out_channels):
        self.w=torch.rand(in_cannels,out_channels)[None][None]
    def forward(x):
        return x@self.w

In [80]:
class Relu(Module):
    def forward(x):
        return x.clamp_min(0)
    def backward():
        self.in.g=(self.in>0).float()*out.g

In [85]:
class Mse(Module):
    def forward(self,x,targ):
        return ((x.squeeze(-1)-targ)**2).mean(dim=1)
    def backward:
        self.in.g=*

In [90]:
temp=torch.rand([5,9])
temp2=torch.rand([5,9])

In [91]:
Mse().forward(temp,temp2)

tensor([0.2029, 0.1852, 0.2095, 0.0806, 0.2006])

In [89]:
temp.squeeze(-1).shape

torch.Size([5, 9, 9])

In [ ]:
    # forward pass:
    l1 = inp @ w1 + b1
    l2 = relu(l1)
    out = l2 @ w2 + b2
    # we don't actually need the loss in backward!
    loss = mse(out, targ)
    
    # backward pass:
    mse_grad(out, targ)
    lin_grad(l2, out, w2, b2)
    relu_grad(l1, l2)
    lin_grad(inp, l1, w1, b1)

In [ ]:
mse(l2(relu(l1(x))),targs)

In [92]:
temp1=torch.rand([3,3])
temp2=torch.rand([3,2])

In [93]:
temp2

tensor([[0.3814, 0.0986],
        [0.3738, 0.7650],
        [0.8969, 0.0609]])

In [94]:
temp1@temp2

tensor([[0.9240, 0.7531],
        [0.7059, 0.7411],
        [0.6752, 0.7215]])

In [95]:
temp1*temp1.t()

tensor([[0.0924, 0.7655, 0.0251],
        [0.7655, 0.7292, 0.0644],
        [0.0251, 0.0644, 0.1251]])